name: Cypress Tests

on:
  push:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, edge]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests for Call_Sling folder
        run: npx cypress run --browser ${{ matrix.browser }} --spec "cypress/e2e/Call_Sling/**/*.cy.{js,ts}"

      - name: Upload Cypress Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Cypress Artifacts ${{ matrix.browser }}
          path: |
            cypress/screenshots
            cypress/videos
