name: Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, edge]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests for Call_Sling folder
        run: npx cypress run --browser ${{ matrix.browser }} --spec "cypress/e2e/Call_Sling/**/*.cy.{js,ts}"

      - name: Upload Cypress Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Cypress Artifacts ${{ matrix.browser }}
          path: |
            cypress/screenshots
            cypress/videos

# Run Cypress Tests for Call_Sling folder - Change here for all files exec
# - name: Run Cypress Tests 
#   uses: cypress-io/github-action@v6 
#   with: browser: ${{ matrix.browser }}

# Parallelization - Cypress will use 3 machines (containers) Below is example:
  # matrix:
  #   containers: [1, 2, 3]

# For mobile apps:
  # matrix:
  #   platform: [android, ios]
  #   device: [Pixel_6, iPhone_13]